version: '3'

services:  
  python279:
    image: 'amarinboonkirt/docker-django'        
    working_dir: /app
    restart: always
    volumes:      
      - './app:/app'
    ports:
      - '${WEBSERVER_PORT}:80'
    links:
      - mariadb
    depends_on:
      - mariadb      
  mariadb:
    image: 'mariadb:10.4'
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    restart: always    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin    
    links:
      - mariadb
    depends_on:
      - mariadb  
    environment:      
      - PMA_HOST=mariadb      
      - PMA_USER=root
      - PMA_PASSWORD=${MARIADB_ROOT_PASSWORD}
    restart: always
    ports:
      - '${PHPMYADMIN_PORT}:80'   